version: "1"
rules:                      # Array of rules
  - base: feature/dotnetcore            # Required. Target branch
    upstream:  phantom-develop    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
label: ":arrow_heading_down: pull"  # Optional